- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: "move backend files to server."
  copy:
    src: files/backend/
    dest: ~/backend

- name: "install package dependencies"
  shell: |
    cd ~/backend
    ls
    npm install

- name: "Copy env vars"
  shell: |
      cd ~/backend
      cat <<EOT >> .env
      ENVIRONMENT= production
      TYPEORM_CONNECTION= "{{ ansible_env.TYPEORM_CONNECTION }}"
      TYPEORM_MIGRATIONS_DIR= "./migrations"
      TYPEORM_MIGRATIONS= "./migrations/*.js"
      TYPEORM_ENTITIES= "./modules/domain/**/*.entity.js"
      TYPEORM_HOST= "{{ ansible_env.TYPEORM_HOST }}"
      TYPEORM_PORT= "{{ ansible_env.TYPEORM_PORT }}"
      TYPEORM_USERNAME= "{{ ansible_env.TYPEORM_USERNAME }}"
      TYPEORM_PASSWORD= "{{ ansible_env.TYPEORM_PASSWORD }}"
      TYPEORM_DATABASE= "{{ ansible_env.TYPEORM_DATABASE }}"
      EOT

- name: "build package"
  shell: |
    cd ~/backend
    npm run build

- name: Executing node
  become: true
  shell: |
    cd ~/backend/dist
    pm2 start npm --name backend -- start
    pm2 ls